# Generated by Django 5.1.8 on 2025-04-19 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=50)),
                ('number_of_keys', models.PositiveIntegerField()),
                ('layout_detail', models.CharField(max_length=100)),
                ('case_spec', models.CharField(max_length=100)),
                ('mounting_style', models.CharField(max_length=50)),
                ('plate_material', models.CharField(max_length=50)),
                ('stab_mount', models.CharField(max_length=50)),
                ('hot_swap', models.BooleanField(default=False)),
                ('knob', models.BooleanField(default=False)),
                ('rgb_type', models.CharField(max_length=100)),
                ('firmware_type', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='keykits/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_kits', to='manufacturers.manufacturer')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'db_table': 'kit',
                'ordering': ['code'],
            },
        ),
    ]
