# Generated by Django 5.1.8 on 2025-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycap',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='switch',
            name='price_per_switch',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
