# Generated by Django 5.1.8 on 2025-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kits/'),
        ),
    ]
