# Generated by Django 5.1.8 on 2025-04-20 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keycap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('legend_type', models.CharField(max_length=100)),
                ('shine_through', models.BooleanField(default=False)),
                ('compatibility', models.CharField(max_length=255)),
                ('number_of_keys', models.PositiveIntegerField()),
                ('layout_support', models.CharField(max_length=100)),
                ('colorway', models.CharField(max_length=100)),
                ('theme_name', models.CharField(max_length=100)),
                ('thickness', models.FloatField()),
                ('texture', models.CharField(max_length=100)),
                ('sound_profile', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='keycaps/')),
                ('price', models.PositiveIntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keycaps', to='manufacturers.manufacturer')),
            ],
            options={
                'verbose_name': 'Keycap',
                'verbose_name_plural': 'Keycaps',
                'db_table': 'keycaps',
                'ordering': ['name'],
            },
        ),
    ]
