# Generated by Django 5.1.8 on 2025-04-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='name',
            new_name='label',
        ),
    ]
