# Generated by Django 5.1.8 on 2025-04-23 03:18

import rolt.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keycaps/', validators=[rolt.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kits/', validators=[rolt.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='switch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='switches/', validators=[rolt.core.validators.validate_file_size]),
        ),
    ]
