# Generated by Django 5.1.8 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_keycap_image_alter_kit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycap',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='switch',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
