# Generated by Django 5.1.8 on 2025-04-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_rename_name_switch_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
