# Generated by Django 5.1.8 on 2025-05-24 08:06

import django.utils.timezone
import rolt.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_keycap_description_kit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanKeycap',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('profile', models.CharField(max_length=100)),
                ('colorway', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artisan_keycaps/', validators=[rolt.core.validators.validate_file_size])),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limited_quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Artisan Keycap',
                'verbose_name_plural': 'Artisan Keycaps',
                'db_table': 'artisan_keycap',
                'ordering': ['-created_at'],
            },
        ),
    ]
