# Generated by Django 5.1.8 on 2025-04-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_keycap_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keycap',
            options={'ordering': ['name'], 'verbose_name': 'Keycap', 'verbose_name_plural': 'Keycaps'},
        ),
        migrations.AlterModelTable(
            name='keycap',
            table='keycap',
        ),
    ]
