# Generated by Django 5.1.8 on 2025-04-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_switch_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='switch',
            table='switch',
        ),
    ]
