# Generated by Django 5.1.8 on 2025-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_artisankeycap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisankeycap',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='keycap',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='kit',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='switch',
            name='price_per_switch',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
