# Generated by Django 5.1.8 on 2025-04-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_types', '0003_alter_componenttype_table'),
        ('components', '0005_stabilizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stabilizer',
            name='mount_type',
        ),
        migrations.AddField(
            model_name='stabilizer',
            name='mount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stabilizer_mount', to='component_types.componenttype'),
        ),
    ]
