# Generated by Django 5.1.8 on 2025-04-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_types', '0003_alter_componenttype_table'),
        ('components', '0006_remove_stabilizer_mount_type_stabilizer_mount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stabilizer',
            name='mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stabilizer_mount', to='component_types.componenttype'),
        ),
    ]
