# Generated by Django 5.1.8 on 2025-04-17 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_table'),
        ('component_types', '0003_alter_componenttype_table'),
        ('components', '0007_alter_stabilizer_mount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keycap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('theme', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='keycaps/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keycap_material', to='component_types.componenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keycap_profile', to='component_types.componenttype')),
            ],
            options={
                'verbose_name': 'Keycap',
                'verbose_name_plural': 'Keycaps',
                'db_table': 'keycap',
                'ordering': ['code'],
            },
        ),
    ]
