# Generated by Django 5.1.8 on 2025-04-17 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_table'),
        ('component_types', '0003_alter_componenttype_table'),
        ('components', '0008_keycap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_material', to='component_types.componenttype')),
                ('mount_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_mount_style', to='component_types.componenttype')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'case',
                'ordering': ['code'],
            },
        ),
    ]
