# Generated by Django 5.1.8 on 2025-05-05 10:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customer_image'),
        ('shop', '0010_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('voided', 'Voided')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='accounts.customer')),
                ('orderitem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='shop.orderitem')),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'db_table': 'warranty',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_requests', to='accounts.customer')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='warranty.warranty')),
            ],
            options={
                'verbose_name': 'Warranty Request',
                'verbose_name_plural': 'Warranty Requests',
                'db_table': 'warranty_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
