# Generated by Django 5.1.8 on 2025-04-24 16:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txn_ref', models.CharField(help_text='Unique transaction code sent to VNPAY (vnp_TxnRef)', max_length=100, unique=True)),
                ('method', models.CharField(choices=[('vnpay', 'VNPAY')], default='vnpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Order amount (VND)', max_digits=12)),
                ('bank_code', models.CharField(blank=True, default='', help_text='Bank code that processed the transaction (vnp_BankCode)', max_length=50)),
                ('vnpay_transaction_no', models.CharField(blank=True, default='', help_text='Transaction number from VNPAY (vnp_TransactionNo)', max_length=100)),
                ('response_code', models.CharField(blank=True, default='', help_text='Response code from VNPAY (vnp_ResponseCode)', max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Payment message/notes')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
