# Generated by Django 5.1.8 on 2025-04-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='vnpay_transaction_no',
            new_name='transaction_no',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='response_code',
        ),
    ]
