volumes:
  rolt_local_postgres_data: {}
  rolt_local_postgres_data_backups: {}
  rolt_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: rolt_local_django
    container_name: rolt_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file: .env
    ports:
      - '8000:8000'
      - '5050:5050'
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: rolt_local_nginx
    container_name: rolt_local_nginx
    depends_on:
      - django
    ports:
      - "80:80"
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: rolt_production_postgres
    container_name: rolt_local_postgres
    volumes:
      - rolt_local_postgres_data:/var/lib/postgresql/data
      - rolt_local_postgres_data_backups:/backups
    env_file: .env
    ports:
      - "5432:5432"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: rolt_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: rolt_local_redis

    volumes:
      - rolt_local_redis_data:/data

  celeryworker:
    <<: *django
    image: rolt_local_celeryworker
    container_name: rolt_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: rolt_local_celerybeat
    container_name: rolt_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: rolt_local_flower
    container_name: rolt_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
