# Generated by Django 5.1.8 on 2025-04-16 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('applies_to', models.CharField(choices=[('switch', 'Switch'), ('keycap', 'Keycap'), ('cable', 'Cable'), ('foam', 'Foam'), ('plate', 'Plate'), ('case', 'Case'), ('pcb', 'PCB'), ('stabilizer', 'Stabilizer'), ('feet', 'Feet')], max_length=50)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Component Type',
                'verbose_name_plural': 'Component Types',
                'ordering': ['code'],
            },
        ),
    ]
