# Generated by Django 5.1.8 on 2025-04-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componenttype',
            old_name='name',
            new_name='label',
        ),
    ]
