# Generated by Django 5.1.8 on 2025-04-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_types', '0002_rename_name_componenttype_label'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='componenttype',
            table='component_type',
        ),
    ]
