# Generated by Django 5.1.8 on 2025-04-23 03:18

import rolt.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturers/', validators=[rolt.core.validators.validate_file_size]),
        ),
    ]
