# Generated by Django 5.1.8 on 2025-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='to',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.EmailField(default='-', max_length=254),
            preserve_default=False,
        ),
    ]
