# Generated by Django 5.1.8 on 2025-04-23 01:57

import rolt.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/images', validators=[rolt.core.validators.validate_file_size]),
        ),
    ]
