# Generated by Django 5.1.8 on 2025-04-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='baseuser',
            table='user',
        ),
    ]
