# Generated by Django 5.1.8 on 2025-05-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_room_alter_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatroom',
            table='chat_rooms',
        ),
    ]
