# Generated by Django 5.1.8 on 2025-04-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_rename_name_brand_label'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
