# Generated by Django 5.1.8 on 2025-04-22 12:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('switch_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_preset', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='accounts.customer')),
                ('keycap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.keycap')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.kit')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.switch')),
            ],
            options={
                'verbose_name': 'Build',
                'verbose_name_plural': 'Builds',
                'db_table': 'build',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='build_showcases/')),
                ('build', models.OneToOneField(limit_choices_to={'is_preset': True}, on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='builds.build')),
            ],
            options={
                'verbose_name': 'Showcase',
                'verbose_name_plural': 'Showcases',
                'db_table': 'showcase',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='builds.build')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.service')),
            ],
            options={
                'db_table': 'selected_service',
                'unique_together': {('build', 'service')},
            },
        ),
    ]
