# Generated by Django 5.1.8 on 2025-04-21 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('switch_quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('is_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='accounts.customer')),
                ('keycap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.keycap')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.kit')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.switch')),
            ],
            options={
                'verbose_name': 'Build',
                'verbose_name_plural': 'Builds',
                'db_table': 'builds',
                'ordering': ['-created_at'],
            },
        ),
    ]
