# Generated by Django 5.1.8 on 2025-04-23 01:57

import rolt.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/', validators=[rolt.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='build_showcases/', validators=[rolt.core.validators.validate_file_size]),
        ),
    ]
