# Generated by Django 5.1.8 on 2025-04-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='keycap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.keycap'),
        ),
        migrations.AddField(
            model_name='build',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.kit'),
        ),
        migrations.AddField(
            model_name='build',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='components.switch'),
        ),
        migrations.AddField(
            model_name='selectedservice',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='builds.build'),
        ),
        migrations.AddField(
            model_name='selectedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.service'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='build',
            field=models.OneToOneField(limit_choices_to={'is_preset': True}, on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='builds.build'),
        ),
        migrations.AlterUniqueTogether(
            name='selectedservice',
            unique_together={('build', 'service')},
        ),
    ]
