# Generated by Django 5.1.8 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_service_image_alter_showcase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
