# Generated by Django 5.1.8 on 2025-04-21 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_build_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='build_showcases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.OneToOneField(limit_choices_to={'is_preset': True}, on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='builds.build')),
            ],
            options={
                'verbose_name': 'Build Showcase',
                'verbose_name_plural': 'Build Showcases',
                'db_table': 'build_showcase',
                'ordering': ['-created_at'],
            },
        ),
    ]
