# Generated by Django 5.1.8 on 2025-04-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
