# Generated by Django 5.1.8 on 2025-04-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_service_options_alter_service_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_default_for_preset',
        ),
    ]
