# Generated by Django 5.1.8 on 2025-05-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_service_description_alter_showcase_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='switch_quantity',
        ),
    ]
