# Generated by Django 5.1.8 on 2025-04-21 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_updated_at_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
