# Generated by Django 5.1.8 on 2025-04-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_build_created_at_alter_showcase_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Showcase', 'verbose_name_plural': 'Showcases'},
        ),
        migrations.AlterModelTable(
            name='showcase',
            table='showcase',
        ),
    ]
