# Generated by Django 5.1.8 on 2025-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_remove_build_switch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='selectedservice',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
