# Generated by Django 5.1.8 on 2025-04-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_remove_service_is_default_for_preset'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selectedservice',
            table='selected_service',
        ),
    ]
