# Generated by Django 5.1.8 on 2025-04-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_alter_showcase_options_alter_showcase_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='build',
            table='build',
        ),
    ]
