# Generated by Django 5.1.8 on 2025-05-24 08:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_artisankeycap'),
        ('inventory', '0003_accessoryinventory_keycapinventory_kitinventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanKeycapInventory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('keycap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_inventory', to='components.artisankeycap')),
            ],
            options={
                'verbose_name': 'Artisan Keycap Inventory',
                'verbose_name_plural': 'Artisan Keycap Inventories',
                'db_table': 'artisan_keycap_inventory',
                'ordering': ['keycap__name'],
            },
        ),
    ]
