# Generated by Django 5.1.8 on 2025-05-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_artisankeycapinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisankeycapinventory',
            options={'ordering': ['artisankeycap__name'], 'verbose_name': 'Artisan Keycap Inventory', 'verbose_name_plural': 'Artisan Keycap Inventories'},
        ),
        migrations.RenameField(
            model_name='artisankeycapinventory',
            old_name='keycap',
            new_name='artisankeycap',
        ),
    ]
