# Generated by Django 5.1.8 on 2025-04-23 01:44

import rolt.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/', validators=[rolt.core.validators.validate_file_size]),
        ),
    ]
