# Generated by Django 5.1.8 on 2025-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_alter_accessory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
