# Generated by Django 5.1.8 on 2025-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_alter_accessory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=14),
        ),
    ]
