log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'

  flower:
    address: ':5555'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'nhatphongcgp@gmail.com'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    redirect-to-www:
      rule: 'Host(`rolt.cloud`)'
      entryPoints:
        - web
        - web-secure
      middlewares:
        - redirect-to-www
      service: noop
      tls:
        certResolver: letsencrypt

    web-secure-router:
      rule: 'Host(`www.rolt.cloud`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    flower-secure-router:
      rule: 'Host(`www.rolt.cloud`) && PathPrefix(`/flower`)'
      entryPoints:
        - flower
      service: flower
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect-to-www:
      redirectRegex:
        regex: '^https?://rolt.cloud/(.*)'
        replacement: 'https://www.rolt.cloud/$1'
        permanent: true

    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    noop:
      loadBalancer:
        servers:
          - url: http://localhost

    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
